name: Update Blocklist
on:
  push:
    paths-ignore:
  schedule:
    - cron: '30 8 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build blocklist
        uses: actions/checkout@v2
      - run: |
          sudo python2 generate-domains-blocklist.py > blocklist.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update blocklist"
          git push
