nname: Update Whitelist

       # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "0 0 * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-blocklist:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build blocklist
        uses: actions/checkout@v2
      - run: |
          chmod +x ./whitelist-aggregator.sh
          ./whitelist-aggregator.sh -o whitelist.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update whitelist"
          git push
